- name: Yum install crontabs
  yum:
    name: crontabs
    state: present

- name: Creates an entry "SHELL"
  cron:
    name: SHELL
    env: yes
    value: /bin/bash

- name: Creates an entry "PATH"
  cron:
    name: PATH
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin:/root/bin:/opt/aws/bin
    insertafter: SHELL

- name: Creates an entry "MAILTO"
  cron:
    name: MAILTO
    env: yes
    value: ""
    insertafter: PATH

- name: copy reboot.sh
  copy: src=reboot.sh dest=/home/elastic/reboot.sh owner=elastic group=elastic mode=744

- name: cron insert elasticsearch restarting
  cron :
    name: elasticsearch
    user: "{{ ansible_user }}"
    special_time: reboot
    job: /home/elastic/reboot.sh

- name: Create a job for shutdown
  cron :
    name: shutdown
    user: root
    minute: 0
    hour: 0
    job: shutdown -h now 2>&1 | logger -t shutdown -p local0.info

