version: '2'
services:
    ansible:
        build: ../ansible
        volumes:
            - .:/var/data
        privileged: true # for use systemctl

    target:
        build: amazonlinux
        privileged: true

