- name: copy reboot.sh
  copy: src=reboot.sh dest=/home/ec2-user/reboot.sh owner=ec2-user group=ec2-user mode=744

- name: cron insert elasticsearch restarting
  cron :
    name: elasticsearch
    user: ec2-user
    special_time: reboot
    job: /home/ec2-user/reboot.sh
