Vagrant.configure("2") do |config|
  config.vm.box = "mvbcoding/awslinux"
  config.vm.hostname = "target"
  config.vm.network :private_network, ip: "192.168.1.41"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.inventory_path = "hosts"
    ansible.limit = 'all'
  end
end
